### ISSUE TITLE
[프론트] greendar_png 파일입니다.

### ISSUE THREAD

**Issue by Arielle0222** [Team-Greendar/greendar#1]
![2](https://user-images.githubusercontent.com/114340019/215017598-9624c0da-36aa-4ddb-baa1-570ea8f42444.png)
![4](https://user-images.githubusercontent.com/114340019/215017599-b920764a-e751-40e2-91f2-eb28f87353ee.png)
![5](https://user-images.githubusercontent.com/114340019/215017600-30dc803b-c807-497a-94b4-e969e4909ce1.png)
![6](https://user-images.githubusercontent.com/114340019/215017601-c7576c78-9322-43a2-abd4-7b69b388819a.png)
![7](https://user-images.githubusercontent.com/114340019/215017603-27d4e45c-1625-4292-99d2-ab7dc7bb8689.png)
![8](https://user-images.githubusercontent.com/114340019/215017605-1d0feb9b-8083-4150-ba78-20f007edf541.png)
![9](https://user-images.githubusercontent.com/114340019/215017607-ee805b3c-c731-4d7a-aa34-3a82d2420678.png)
![10](https://user-images.githubusercontent.com/114340019/215017611-1f11c308-2ec7-44b0-9b9f-8cc94d795e60.png)

**Comment by chosunghyun18** [comment]
good
